// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/first-steps/index.mdx?collection=docs&hash=1757930169632"
import * as docs_8 from "../content/docs/first-steps/getting-started.mdx?collection=docs&hash=1757930169632"
import * as docs_7 from "../content/docs/(next)/server-client.mdx?collection=docs&hash=1757930169632"
import * as docs_6 from "../content/docs/(next)/route-handlers.mdx?collection=docs&hash=1757930169632"
import * as docs_5 from "../content/docs/(next)/middleware.mdx?collection=docs&hash=1757930169632"
import * as docs_4 from "../content/docs/(next)/metadata.mdx?collection=docs&hash=1757930169632"
import * as docs_3 from "../content/docs/(next)/images.mdx?collection=docs&hash=1757930169632"
import * as docs_2 from "../content/docs/(next)/data-fetching.mdx?collection=docs&hash=1757930169632"
import * as docs_1 from "../content/docs/(next)/app-router.mdx?collection=docs&hash=1757930169632"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1757930169632"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"(next)\\app-router.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/(next)/app-router.mdx"}, data: docs_1 }, { info: {"path":"(next)\\data-fetching.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/(next)/data-fetching.mdx"}, data: docs_2 }, { info: {"path":"(next)\\images.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/(next)/images.mdx"}, data: docs_3 }, { info: {"path":"(next)\\metadata.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/(next)/metadata.mdx"}, data: docs_4 }, { info: {"path":"(next)\\middleware.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/(next)/middleware.mdx"}, data: docs_5 }, { info: {"path":"(next)\\route-handlers.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/(next)/route-handlers.mdx"}, data: docs_6 }, { info: {"path":"(next)\\server-client.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/(next)/server-client.mdx"}, data: docs_7 }, { info: {"path":"first-steps\\getting-started.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/first-steps/getting-started.mdx"}, data: docs_8 }, { info: {"path":"first-steps\\index.mdx","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/first-steps/index.mdx"}, data: docs_9 }], [{"info":{"path":"meta.yaml","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/meta.yaml"},"data":{"title":"Документация","pages":["index","first-steps","(next)","..."]}}, {"info":{"path":"(next)\\meta.yaml","absolutePath":"C:/Users/HP/Desktop/nunto_ai/content/docs/(next)/meta.yaml"},"data":{"title":"Next.js — основы","pages":["app-router","data-fetching","server-client","metadata","images","route-handlers","middleware"]}}])