import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AccentColorApplier } from "@/components/accent-color-applier";

export const metadata: Metadata = {
  title: "Nunto AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={``}>
        <Toaster position="top-right" />
        <AccentColorApplier />
        {children}
      </body>
    </html>
  );
}
