import type { Metadata } from "next";
import "../globals.css";
import { ThemeProviders } from "@/components/providers/theme-provider";
export const metadata: Metadata = {
  title: "Nunto AI",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <ThemeProviders>
        <body className={`bg-orange-100`}>{children}</body>
      </ThemeProviders>{" "}
    </html>
  );
}
