import type { Metadata } from "next";
import "../globals.css";
export const metadata: Metadata = {
  title: "Nunto AI",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`bg-orange-100`}>{children}</body>
    </html>
  );
}
