import type { Metadata } from "next";
import "../globals.css";
import { Providers } from "@/components/providers/Providers";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Nunto AI",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="ru">
      <body className={``}>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
