import type { Metadata } from "next";
import "../globals.css";
import { Providers } from "@/components/providers/Providers";
import { getServerSession } from "next-auth";
import { prisma } from "@/prisma/prisma-client";
import { authOptions } from "@/lib/auth";
import { AccentColorApplier } from "@/components/accent-color-applier";

export const metadata: Metadata = {
  title: "Nunto AI",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const chats = await prisma.chat.findMany({
    where: { userId: Number(session?.user?.id) },
  });
  return (
    <html lang="ru">
      <body>
        <Providers chats={chats}>
          <AccentColorApplier />
          {children}
        </Providers>
      </body>
    </html>
  );
}
